### ISSUE TITLE
Errors during RPM build

### ISSUE THREAD

**Issue by mmamajiwala** [juliogonzalez/pgsql-http-rpm#2]
Hello,

Please see the below errors during the RPM build.

 ./pgsql-http-rpm -p 9.3 for PostgreSQL 9.3
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Rp70s8
+ umask 022
+ cd /root/pgsql-http-rpm/BUILD
+ cd /root/pgsql-http-rpm/BUILD
+ rm -rf pgsql-http-a58d9d24acb982ab71ffb95c45fb48063f5a86a6
+ /bin/tar -xf -
+ /usr/bin/gzip -dc /root/pgsql-http-rpm/SOURCES/a58d9d24acb982ab71ffb95c45fb48063f5a86a6.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd pgsql-http-a58d9d24acb982ab71ffb95c45fb48063f5a86a6
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.STgaUZ
+ umask 022
+ cd /root/pgsql-http-rpm/BUILD
+ cd pgsql-http-a58d9d24acb982ab71ffb95c45fb48063f5a86a6
+ PATH=/usr/pgsql-9.3/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin
+ make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fpic -I. -I. -I/usr/include/pgsql93/server -I/usr/include/pgsql93/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o http.o http.c
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fpic -shared -o http.so http.o -L/usr/lib64/pgsql93 -Wl,--as-needed  -lcurl
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.6wiT1R
+ umask 022
+ cd /root/pgsql-http-rpm/BUILD
+ cd pgsql-http-a58d9d24acb982ab71ffb95c45fb48063f5a86a6
+ rm -rf /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64
+ PATH=/usr/pgsql-9.3/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin
+ make install DESTDIR=/root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64
/bin/mkdir -p '/root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/lib64/pgsql93'
/bin/mkdir -p '/root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/share/pgsql93/extension'
/bin/mkdir -p '/root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/share/pgsql93/extension'
/usr/bin/install -c -m 755  http.so '/root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/lib64/pgsql93/http.so'
/usr/bin/install -c -m 644 ./http.control '/root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/share/pgsql93/extension/'
/usr/bin/install -c -m 644 ./http--1.1.sql ./http--1.0--1.1.sql  '/root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/share/pgsql93/extension/'
+ mkdir -p /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/share/doc/postgresql-93-pgsql-http
+ cp README.md /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/share/doc/postgresql-93-pgsql-http/README.md
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
Processing files: postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64
error: File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/lib/http.so
error: File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/share/extension/http--1.1.sql
error: File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/share/extension/http--1.0--1.1.sql
error: File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/share/extension/http.control

RPM build errors:
    File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/lib/http.so
    File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/share/extension/http--1.1.sql
    File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/share/extension/http--1.0--1.1.sql
    File not found: /root/pgsql-http-rpm/BUILDROOT/postgresql-93-pgsql-http-1.1.1-2gita58d9d2.amzn1.x86_64/usr/pgsql-9.3/share/extension/http.control
There are errors. Check your log.

Do let me know if you need any further details.

Thanks
Mohammad

**Comment by juliogonzalez** [comment]
@mmamajiwala, are your PostgreSQL packages (postgres93-devel) being installed from the AWS repositories, or from the official PostgreSQL repositories?

Please run:

```
yum info postgresql93-devel
```

And paste the output.

**Comment by mmamajiwala** [comment]
I think it is installed from the AWS repositories.  Please see the below output.

[ec2-user@ip-172-31-37-200 ~]$ sudo yum info postgresql93-devel
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
Name        : postgresql93-devel
Arch        : x86_64
Version     : 9.3.14
Release     : 1.62.amzn1
Size        : 4.1 M
Repo        : installed
From repo   : amzn-main
Summary     : PostgreSQL development header files and libraries
URL         : http://www.postgresql.org/
License     : PostgreSQL
Description : The postgresql-devel package contains the header files and libraries
            : needed to compile C or C++ applications which will directly interact
            : with a PostgreSQL database management server.  It also contains the ecpg
            : Embedded C Postgres preprocessor. You need to install this package if you want
            : to develop applications which will interact with a PostgreSQL server.

**Comment by juliogonzalez** [comment]
Yes, you can see it at "From repo" line.

Try to use the official packages [1], as the RPM expects all the stuff to be at the same path where the official packages place it.

For example, notice that it's installing the library as /usr/lib64/pgsql93/http.so (at the BUILDROOT) while it should install it as /usr/pgsql-9.3/lib/http.so

[1] https://yum.postgresql.org/

**Comment by mmamajiwala** [comment]
Thanks. I will try it and let you know how it goes.

**Comment by juliogonzalez** [comment]
BTW, I added the new SPEC to support pgsql-http 1.1.2 in case you want to give it a try :-)

**Comment by mmamajiwala** [comment]
Shall I remove complete PostgreSQL and install it again?

**Comment by juliogonzalez** [comment]
That depends on what YUM tells you when you try to remove just posgresql92-devel and reinstall it from the official repositories.

If it works, then I think you don't need to reinstall PosgreSQL, so give it a try.

But if you try to reinstall posgresql92-devel from the official repositories, and YUM complains... then yes, you will need to completely remove PostgreSQL and install it again.

**Comment by mmamajiwala** [comment]
I will try it. Thanks!

**Comment by juliogonzalez** [comment]
Discussed offline and fixed.

The problem is that the current RPM SPEC only supports the [official PosgreSQL RPM packages](https://yum.postgresql.org/).

README.md modified at 1a48d1e to specify this.

@mmamajiwala if the problem is fixed, can you close the issue?

Thanks!

**Comment by mmamajiwala** [comment]
After using official PostgreSQL RPM package, the problem has been resolved. It worked as expected.

Thanks for all your help.
